/**
 * FILE: src/constants/nameMeanings.ts
 * Dataset of 50+ common names for ASTRAL Name Analysis
 */

export interface NameInfo {
  meaning: string;
  traits: string[];
  uzMeaning: string;
  uzTraits: string[];
}

export const NAME_MEANINGS: Record<string, NameInfo> = {
  ali: {
    meaning: "Elevated, noble, high-ranking",
    traits: ["Leadership", "Confidence", "Strong will"],
    uzMeaning: "Yuksak, oliyjanob, baland darajali",
    uzTraits: ["Yetakchilik", "O'ziga ishonch", "Kuchli iroda"],
  },
  muhammad: {
    meaning: "Praised, highly respected",
    traits: ["Wisdom", "Calmness", "Responsibility"],
    uzMeaning: "Maqtovga loyiq",
    uzTraits: ["Donolik", "Vazminlik", "Mas'uliyat"],
  },
  sara: {
    meaning: "Princess, noble woman",
    traits: ["Kindness", "Intuition", "Emotional depth"],
    uzMeaning: "Malika, oliyjanob ayol",
    uzTraits: ["Mehribonlik", "Intuitsiya", "Hissiyotlarga boy"],
  },
  amir: {
    meaning: "Prince, commander, ruler",
    traits: ["Authority", "Ambition", "Protection"],
    uzMeaning: "Hukmdor, boshliq",
    uzTraits: ["Obro'", "Ambitsiya", "Himoyachilik"],
  },
  layla: {
    meaning: "Night, dark beauty",
    traits: ["Mystery", "Grace", "Creativity"],
    uzMeaning: "Tun, qorong'u go'zallik",
    uzTraits: ["Sirli", "Lofotat", "Ijodkorlik"],
  },
  aziz: {
    meaning: "Beloved, powerful, dear",
    traits: ["Loyalty", "Strength", "Respect"],
    uzMeaning: "Qadrli, aziz, qudratli",
    uzTraits: ["Sodiqlik", "Kuch", "Hurmat"],
  },
  dilorom: {
    meaning: "Heart's ease, peace of soul",
    traits: ["Gentleness", "Patience", "Harmony"],
    uzMeaning: "Dil oromi, ko'ngil tinchligi",
    uzTraits: ["Muloyimlik", "Sabr", "Garmoniya"],
  },
  bekzod: {
    meaning: "Born of a nobleman",
    traits: ["Dignity", "Bravery", "Strategic thinking"],
    uzMeaning: "Beklar avlodidan",
    uzTraits: ["Qadr-qimmat", "Jasorat", "Strategik fikrlash"],
  },
  nigina: {
    meaning: "Gemstone, precious stone",
    traits: ["Sparkle", "Precision", "Value"],
    uzMeaning: "Qimmatbaho tosh, uzuk ko'zi",
    uzTraits: ["Yorqinlik", "Aniqlik", "Qadrlilik"],
  },
  rustam: {
    meaning: "Strong, hero, legendary power",
    traits: ["Heroism", "Physical power", "Unyielding spirit"],
    uzMeaning: "Baquvvat, qahramon",
    uzTraits: ["Qahramonlik", "Jismoniy kuch", "Bukulmas iroda"],
  },
  zuhra: {
    meaning: "Brilliant, flower, Venus planet",
    traits: ["Beauty", "Radiance", "Artistic talent"],
    uzMeaning: "Yorqin, gul, Zuhro sayyorasi",
    uzTraits: ["Go'zallik", "Nurlilik", "Badiiy iqtidor"],
  },
  farhod: {
    meaning: "Happy, quick-witted, clever",
    traits: ["Intelligence", "Speed", "Joy"],
    uzMeaning: "Baxtli, aqlli",
    uzTraits: ["Intellekt", "Tezkorlik", "Shodlik"],
  },
  madina: {
    meaning: "City, the enlightened city",
    traits: ["Spirituality", "Order", "Cleanliness"],
    uzMeaning: "Shahar, Madina shahri",
    uzTraits: ["Ma'naviyat", "Tartib", "Poklik"],
  },
  nodir: {
    meaning: "Rare, unique, excellent",
    traits: ["Originality", "Exclusivity", "Quality"],
    uzMeaning: "Noyob, kamyob",
    uzTraits: ["O'ziga xoslik", "Eksklyuzivlik", "Sifat"],
  },
  shaxlo: {
    meaning: "Beautiful eyes, attractive",
    traits: ["Observation", "Charm", "Femininity"],
    uzMeaning: "Chiroyli ko'zli, go'zal",
    uzTraits: ["Kuzatuvchanlik", "Joziba", "Latofat"],
  },
  abbos: {
    meaning: "Stern, lion",
    traits: ["Courage", "Seriousness", "Focus"],
    uzMeaning: "Qovog'i soliq, arslon",
    uzTraits: ["Jasorat", "Jiddiylik", "Fokus"],
  },
  anvar: {
    meaning: "Brightest, luminous",
    traits: ["Optimism", "Clarity", "Warmth"],
    uzMeaning: "Nurlari ko'p, yorqin",
    uzTraits: ["Optimizm", "Aniqlik", "Iliq munosabat"],
  },
  jasur: {
    meaning: "Brave, daring",
    traits: ["Risk-taking", "Fearlessness", "Directness"],
    uzMeaning: "Jasur, qo'rqmas",
    uzTraits: ["Tavakkalchi", "Qo'rqmaslik", "To'g'riso'zlik"],
  },
  nilufar: {
    meaning: "Water lily, lotus",
    traits: ["Purity", "Resilience", "Stillness"],
    uzMeaning: "Nilufar guli",
    uzTraits: ["Poklik", "Chidamlilik", "Vazminlik"],
  },
  umid: {
    meaning: "Hope",
    traits: ["Aspiration", "Positivity", "Long-term vision"],
    uzMeaning: "Umid",
    uzTraits: ["Intilish", "Ijobiylik", "Kelajakka ishonch"],
  },
  shirin: {
    meaning: "Sweet, pleasant",
    traits: ["Friendliness", "Elegance", "Hostess"],
    uzMeaning: "Shirin, yoqimli",
    uzTraits: ["Do'stonalik", "Nafosat", "Mehmondo'stlik"],
  },
  botir: {
    meaning: "Brave warrior, hero",
    traits: ["Protection", "Steadfastness", "Honesty"],
    uzMeaning: "Botir, pahlavon",
    uzTraits: ["Himoyachilik", "Sodiqlik", "Rostgo'ylik"],
  },
  malika: {
    meaning: "Queen, princess",
    traits: ["Sovereignty", "High standards", "Charity"],
    uzMeaning: "Malika, xonim",
    uzTraits: ["Mustaqillik", "Yuqori talablar", "Saxovat"],
  },
  oybek: {
    meaning: "Lord as the moon",
    traits: ["Reflectiveness", "Calm leadership", "Logic"],
    uzMeaning: "Oydek chiroyli bek",
    uzTraits: ["Mulohaza", "Vazmin yetakchilik", "Mantiq"],
  },
  gavhar: {
    meaning: "Jewel, pearl",
    traits: ["Inner beauty", "Depth", "Persistence"],
    uzMeaning: "Gavhar, marvarid",
    uzTraits: ["Ichki go'zallik", "Chuqurlik", "Qat'iyatlilik"],
  },
  islom: {
    meaning: "Surrender (to God), peace",
    traits: ["Faith", "Peacefulness", "Justice"],
    uzMeaning: "Islom, tinchlik",
    uzTraits: ["Iymon", "Tinchliksevarlik", "Adolat"],
  },
  gozal: {
    meaning: "Beautiful",
    traits: ["Aesthetics", "Grace", "Empathy"],
    uzMeaning: "Go'zal",
    uzTraits: ["Estetika", "Latofat", "Hamdardlik"],
  },
  temur: {
    meaning: "Iron",
    traits: ["Indestructibility", "Iron will", "Strictness"],
    uzMeaning: "Temir",
    uzTraits: ["Mustahkamlik", "Temir iroda", "Qat'iyatlilik"],
  },
  sevara: {
    meaning: "Beloved",
    traits: ["Affection", "Warmth", "Loyalty"],
    uzMeaning: "Sevimli",
    uzTraits: ["Mehr-muhabbat", "Illiqlik", "Sodiqlik"],
  },
  oila: {
    meaning: "Family, lineage",
    traits: ["Nurturing", "Bonding", "Tradition"],
    uzMeaning: "Oila",
    uzTraits: ["G'amxo'rlik", "Bog'liqlik", "An'analar"],
  },
  jonibek: {
    meaning: "Dear nobleman",
    traits: ["Soulfulness", "Kindness", "Community"],
    uzMeaning: "Aziz bek",
    uzTraits: ["Samimiylik", "Mehr", "Jamoaviylik"],
  },
  feruza: {
    meaning: "Turquoise, victorious",
    traits: ["Clarity", "Success", "Radiance"],
    uzMeaning: "Firuza toshi, g'olib",
    uzTraits: ["Aniqlik", "Muvaffaqiyat", "Yorqinlik"],
  },
  davron: {
    meaning: "Era, time, rotation",
    traits: ["Adaptability", "Modernity", "Progress"],
    uzMeaning: "Davron, vaqt",
    uzTraits: ["Moslashuvchanlik", "Zamonaviylik", "Progress"],
  },
  akmal: {
    meaning: "Perfect, complete",
    traits: ["Perfectionism", "Completion", "Mastery"],
    uzMeaning: "Mukammal",
    uzTraits: ["Mukammallikka intilish", "Yakunlash", "Mahorat"],
  },
  dilyara: {
    meaning: "Beautiful friend",
    traits: ["Friendship", "Support", "Grace"],
    uzMeaning: "Go'zal oroy",
    uzTraits: ["Do'stlik", "Qo'llab-quvvatlash", "Latofat"],
  },
  ulugbek: {
    meaning: "Great lord",
    traits: ["Vast knowledge", "Governance", "Authority"],
    uzMeaning: "Ulug' bek",
    uzTraits: ["Bilimdonlik", "Boshqaruv", "Nufuz"],
  },
  shaxnoz: {
    meaning: "The pride of kings",
    traits: ["Pride", "Exclusivity", "Artistry"],
    uzMeaning: "Shohlar nozi",
    uzTraits: ["Faxr", "Eksklyuzivlik", "San'atsevarlik"],
  },
  kamol: {
    meaning: "Fullness, perfection",
    traits: ["Maturity", "Stability", "Wholeness"],
    uzMeaning: "Kamolot",
    uzTraits: ["Voyaga yetganlik", "Barqarorlik", "Butunlik"],
  },
  asila: {
    meaning: "Noble, original",
    traits: ["Authenticity", "Pure intent", "Heritage"],
    uzMeaning: "Asl, oliyjanob",
    uzTraits: ["Haqiqiylik", "Pok niyat", "Meros"],
  },
  sarvar: {
    meaning: "Leader, head",
    traits: ["Directive", "Initiative", "Stability"],
    uzMeaning: "Yo'lboshchi, rahbar",
    uzTraits: ["Boshqaruvchi", "Tashabbuskorlik", "Barqarorlik"],
  },
  guli: {
    meaning: "Flower",
    traits: ["Gentleness", "Fragility", "Growth"],
    uzMeaning: "Gul",
    uzTraits: ["Noziklik", "Nafoat", "O'sish"],
  },
  islombek: {
    meaning: "Islamic lord",
    traits: ["Devotion", "Respect", "Tradition"],
    uzMeaning: "Islomiy bek",
    uzTraits: ["Sodiqlik", "Hurmat", "An'ana"],
  },
  nodira: {
    meaning: "Rare woman",
    traits: ["Creativity", "Eloquence", "Sophistication"],
    uzMeaning: "Noyob ayol",
    uzTraits: ["Ijodkorlik", "Notiqlik", "Murakkablik"],
  },
  bekpulat: {
    meaning: "Steel nobleman",
    traits: ["Endurance", "Reliability", "Defense"],
    uzMeaning: "Po'latdek mustahkam bek",
    uzTraits: ["Chidamlilik", "Ishonchlilik", "Himoya"],
  },
  dilnoza: {
    meaning: "Heart's pride",
    traits: ["Self-respect", "Sensitivity", "Elegance"],
    uzMeaning: "Dil nozi",
    uzTraits: ["O'z-o'zini hurmat qilish", "Ta'sirchanlik", "Nafosat"],
  },
  umidabegim: {
    meaning: "Hopeful lady",
    traits: ["Optimism", "Community focus", "Grace"],
    uzMeaning: "Umidli begim",
    uzTraits: ["Yaxshi niyat", "Jamoaviylik", "Latofat"],
  },
  rustambek: {
    meaning: "Strong lord",
    traits: ["Command", "Force", "Loyalty"],
    uzMeaning: "Kuchli bek",
    uzTraits: ["Buyruq", "Kuch", "Sodiqlik"],
  },
  shaxrizod: {
    meaning: "Child of a great city",
    traits: ["Storytelling", "Intellect", "Survival"],
    uzMeaning: "Shahar farzandi",
    uzTraits: ["Hikoyachilik", "Intellekt", "Omon qolish"],
  },
  olim: {
    meaning: "Learned, scholar",
    traits: ["Curiosity", "Logic", "Teaching"],
    uzMeaning: "Bilimdon, olim",
    uzTraits: ["Qiziquvchanlik", "Mantiq", "O'rgatish"],
  },
  nafisa: {
    meaning: "Refined, precious",
    traits: ["Taste", "Attention to detail", "Softness"],
    uzMeaning: "Nafis, qimmatli",
    uzTraits: ["Did", "Tafsilotlarga e'tibor", "Yumshoqlik"],
  },
  umrbek: {
    meaning: "Lord of life",
    traits: ["Vitality", "Legacy", "Experience"],
    uzMeaning: "Uzoq umrli bek",
    uzTraits: ["Hayotiylik", "Meros", "Tajriba"],
  },
};

export const LETTER_ANALYSIS: Record<string, { en: string; uz: string; trait: string; uzTrait: string }> = {
  a: { en: "Ambition", uz: "Ambitsiya", trait: "Born leader, always looking forward.", uzTrait: "Tug'ilgan yetakchi, doim oldinga intiladi." },
  b: { en: "Balance", uz: "Muvozanat", trait: "Harmonious and peaceful nature.", uzTrait: "Garmoniya va tinchliksevarlik." },
  c: { en: "Creativity", uz: "Ijodkorlik", trait: "Artistic and expressive soul.", uzTrait: "Badiiy va ifodali ruh." },
  d: { en: "Determination", uz: "Qat'iyat", trait: "Focused and hardworking.", uzTrait: "Fokusni yo'qotmaydigan mehnatkash." },
  e: { en: "Energy", uz: "Energiya", trait: "Active and enthusiastic.", uzTrait: "Faol va g'ayratli." },
  f: { en: "Faith", uz: "Ishonch", trait: "Loyal and dependable friend.", uzTrait: "Sodiq va ishonchli do'st." },
  g: { en: "Grace", uz: "Latofat", trait: "Elegant and sophisticated.", uzTrait: "Nafis va murakkab." },
  h: { en: "Honesty", uz: "Rostgo'ylik", trait: "Transparent and true.", uzTrait: "Ochiqko'ngil va haqiqatgo'y." },
  i: { en: "Intuition", uz: "Intuitsiya", trait: "Smart and deeply insightful.", uzTrait: "Aqlli va chuqur mulohazali." },
  j: { en: "Joy", uz: "Shodlik", trait: "Spreads happiness everywhere.", uzTrait: "Hamma joyda baxt ulashadi." },
  k: { en: "Kindness", uz: "Mehribonlik", trait: "Generous and helpful.", uzTrait: "Saxiy va yordamga tayyor." },
  l: { en: "Logic", uz: "Mantiq", trait: "Analytical and clear-headed.", uzTrait: "Analitik va aniq fikrlovchi." },
  m: { en: "Motivation", uz: "Motivatsiya", trait: "Driven and inspiring.", uzTrait: "Harakatlantiruvchi va ilhomlantiruvchi." },
  n: { en: "Nobility", uz: "Oliyjanoblik", trait: "Principled and dignified.", uzTrait: "Prinsipial va qadrli." },
  o: { en: "Originality", uz: "O'ziga xoslik", trait: "Unique and creative.", uzTrait: "Noyob va ijodkor." },
  p: { en: "Patience", uz: "Sabr", trait: "Calm under pressure.", uzTrait: "Bosim ostida ham xotirjam." },
  q: { en: "Quest", uz: "Izlanish", trait: "Always searching for truth.", uzTrait: "Doim haqiqatni qidiradi." },
  r: { en: "Resilience", uz: "Chidamlilik", trait: "Strong and unyielding.", uzTrait: "Kuchli va bukilmas." },
  s: { en: "Stability", uz: "Barqarorlik", trait: "Reliable and steady.", uzTrait: "Ishonchli va doimiy." },
  t: { en: "Thoughtfulness", uz: "Mulohaza", trait: "Caring and observant.", uzTrait: "G'amxo'r va kuzatuvchan." },
  u: { en: "Unity", uz: "Birlik", trait: "Brings people together.", uzTrait: "Odamlarni birlashtiradi." },
  v: { en: "Victory", uz: "G'alaba", trait: "Always strives to win.", uzTrait: "Doim g'alabaga intiladi." },
  w: { en: "Wisdom", uz: "Donolik", trait: "Smarter than their years.", uzTrait: "Yoshidan ko'ra aqlliroq." },
  x: { en: "X-factor", uz: "Istora", trait: "Has a magnetic personality.", uzTrait: "Magnit kabi tortadigan joziba." },
  y: { en: "Youthfulness", uz: "Yoshlik", trait: "Vibrant and energetic.", uzTrait: "Hayotiy va g'ayratli." },
  z: { en: "Zen", uz: "Zukkoli", trait: "Found inner peace and focus.", uzTrait: "Ichki xotirjamlikni topgan." },
};
